// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IResponse is an autogenerated mock type for the IResponse type
type IResponse struct {
	mock.Mock
}

// GetStatusCode provides a mock function with given fields:
func (_m *IResponse) GetStatusCode() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatusCode")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// NewIResponse creates a new instance of IResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *IResponse {
	mock := &IResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
