version: '3.8'
networks:
  service-conn:
    driver: bridge

services:
  postgres-user:
    image: postgres:14.12
    container_name: postgres-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    networks:
      - service-conn
  user-simple-crud-web:
    build: .
    command: ["./user-simple-crud-web"]
    ports:
      - "9004:9004"
    networks:
      - service-conn
    environment:
      APP_NAME: "user-simple-crud"
      APP_ENV: "development"
      GIN_MODE: "release"
      APP_DEBUG: "true"
      APP_VERSION: "v1"
      HTTP_PORT: "9004"
      JWT_SECRET_ACCESS_TOKEN: "wkhB8NarrReKujasQzlRaOQGOO4S1G884ol9SIyQ7Fr4zxLBJI9Ezml4DeaisAss"
      DB_CONNECTION: "postgres"
      DB_HOST: "postgres-user"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "user"
      DB_PREFIX: "example_"
      ALLOW_ORIGINS: "*"
      ALLOW_METHODS: "POST,GET,PUT,DELETE,OPTIONS"
      ALLOW_HEADERS: "*"
      LOG_PATH: "./logs/"
    restart: on-failure
